services:
  forspark-mongo:
    image: mongo:6
    container_name: forspark-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  forspark-python-api:
    build: ./Pythonbackend
    container_name: forspark-python-api
    env_file:
      - ./Pythonbackend/.env
    ports:
      - "5001:5001"

  forspark-node-api:
    build: ./backend
    container_name: forspark-node-api
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - forspark-mongo
      - forspark-python-api

  forspark-frontend:
    build: ./frontend
    container_name: forspark-frontend
    ports:
      - "3000:80"
    depends_on:
      - forspark-node-api

volumes:
  mongo_data:
